README.org ---  description



Copyright (C) 2005-2019 Roman V. Prikhodchenko



Author: Roman V. Prikhodchenko <chujoii@gmail.com>

  This file is part of lisp-perceptron.

  lisp-perceptron is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  lisp-perceptron is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with lisp-perceptron.  If not, see <http://www.gnu.org/licenses/>.


  Documentation is licensed under a Creative Commons
  Attribution-ShareAlike 3.0 Unported License.

* Keywords:
lisp scheme simple perceptron
  

* Description:
simple perceptron (lisp scheme)
  
  
* Usage:
read with emacs (3__3) org mode

* History:
initial project version began about 2019.08(Aug).28

* Dependences:
+ [[https://www.gnu.org/software/guile/][dev-scheme/guile]] GNU Ubiquitous Intelligent Language for Extensions
  (GNU Guile) --- implementation of the programming language Scheme
  (Lisp dialect).
  LICENSE="LGPL-3+"

* Code:
